apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-demo-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-demo-py
  template:
    metadata:
      labels:
        app: gh-demo-py
    spec:
      containers:
      - name: gh-demo-py
        image: yrj9920/gh-demo
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gh-demo-py-service
spec:
  type: NodePort
  selector:
    app: gh-demo-py
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # NodePort field is optional. If not specified, Kubernetes will allocate a port automatically.
      # nodePort: 30007