name: CICD

on:
  push:
   branches: [ main ]  
  workflow_dispatch:  

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # # Build and push Docker image
    # - name: Build Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: false
    #     tags: gh-demo/request-logger:${{ github.sha}}
    #     file: Dockerfile-multi
    #     cache-from: type=local,src=/tmp/.buildx-cache
    #     cache-to: type=local,dest=/tmp/.buildx-cache
    #     load: true

    # # Test the deployment
    # - name: Test
    #   run: |
    #     sudo apt-get update && sudo apt-get install -y curl
    #     docker run -d --name logger -p 8080:8080 gh-demo/request-logger:${{ github.sha}}
    #     while ! curl -s http://localhost:8080/health | grep -q "OK"; do sleep 30;curl -s http://localhost:8080/health;exit; done

    # Build and push Docker image
    - name: Build Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: gh-demo/flask-demo:${{ github.sha}}
        file: Dockerfile
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache