name: CICD-K8s

on:
  # push:
  #  branches: [ main ]  
  workflow_dispatch:  

jobs:
  Deploy-K8s-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Set up Kubernetes in Docker (KIND)
    - name: Create KIND Cluster
      uses: helm/kind-action@v1

    # Deploy to KIND Cluster
    - name: Deploy to KIND
      env:
        SHA_TAG: ${{vars.GH_DEMO_DOCKER_TAG}}
      run: |
        echo "Tag: $SHA_TAG"
        TAG=$SHA_TAG envsubst '${TAG}' < deployment.yaml > final_deployment.yaml
        kubectl apply -f final_deployment.yaml

    # Test the deployment
    - name: Test
      run: |
        kubectl wait --for=condition=Ready pod -l app=gh-demo-py --timeout=300s
        # Add commands to test the application
        # For instance, using curl to check if the app responds correctly
        NODE_PORT=$(kubectl get svc gh-demo-py-service -o=jsonpath='{.spec.ports[0].nodePort}')
        NODE_IP=$(kubectl get nodes -o=jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        curl -s $NODE_IP:$NODE_PORT/hello

    